package com.model;

/**
 * TToupiaoxuanxiang generated by MyEclipse Persistence Tools
 */

public class TToupiaoxuanxiang implements java.io.Serializable
{

	private String id;
	private String xuanxiangneirong;
	private Integer piaoshu;
	private String toupiao_id;
	private String toupiao_rel_id;
	
	private String label;
	
	
	public String getId()
	{
		return id;
	}
	public void setId(String id)
	{
		this.id = id;
	}
	public Integer getPiaoshu()
	{
		return piaoshu;
	}
	public void setPiaoshu(Integer piaoshu)
	{
		this.piaoshu = piaoshu;
	}
	
	public String getToupiao_id()
	{
		return toupiao_id;
	}
	public void setToupiao_id(String toupiao_id)
	{
		this.toupiao_id = toupiao_id;
	}
	public String getXuanxiangneirong()
	{
		return xuanxiangneirong;
	}
	public void setXuanxiangneirong(String xuanxiangneirong)
	{
		this.xuanxiangneirong = xuanxiangneirong;
	}
	public String getToupiao_rel_id() {
		return toupiao_rel_id;
	}
	public void setToupiao_rel_id(String toupiao_rel_id) {
		this.toupiao_rel_id = toupiao_rel_id;
	}
	public String getLabel() {
		return label;
	}
	public void setLabel(String label) {
		this.label = label;
	}

}